# Generated by Django 3.2.7 on 2021-09-13 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('duedate', models.DateTimeField()),
                ('sub_details', models.TextField()),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/forum/')),
                ('filetype', models.CharField(choices=[('file', 'File'), ('text', 'Text'), ('url', 'URL')], max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/forum/')),
                ('postsub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.submissions')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
