# Generated by Django 3.2.7 on 2021-09-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
    ]
