# Generated by Django 3.2.7 on 2021-09-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
