# Generated by Django 3.2.7 on 2021-09-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_alter_subject_faculty_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='faculty_id',
            new_name='cp_id',
        ),
    ]
