# Generated by Django 3.2.7 on 2021-09-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_rename_faculty_id_subject_cp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course_id',
        ),
    ]
