# Generated by Django 3.2.7 on 2021-09-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_alter_subject_cp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
